CREATE TABLE `halls` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `location` varchar(255) NOT NULL,
  `city` varchar(100) NOT NULL,
  `state` varchar(100) DEFAULT NULL,
  `price_per_hour` decimal(10,2) NOT NULL,
  `capacity` int NOT NULL,
  `description` text DEFAULT NULL,
  `image_url` text DEFAULT NULL,
  `images` json DEFAULT NULL,
  `amenities` json DEFAULT NULL,
  `type` varchar(100) DEFAULT 'Banquet Hall',
  `rating` decimal(3,2) DEFAULT '4.5',
  `total_reviews` int DEFAULT '0',
  `is_verified` tinyint(1) DEFAULT '1',
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_location` (`location`),
  KEY `idx_city` (`city`),
  KEY `idx_price` (`price_per_hour`),
  KEY `idx_capacity` (`capacity`),
  KEY `idx_rating` (`rating`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=120001